# Generated by Django 5.1.5 on 2025-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='fsdfssdfsdfsfsdfsf'),
            preserve_default=False,
        ),
    ]
