# Generated by Django 5.1.5 on 2025-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='sdfsfdsdfsdfsfsfdsdf'),
            preserve_default=False,
        ),
    ]
