# Generated by Django 5.1.5 on 2025-02-22 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_discount_price_orderitem_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='item',
        ),
    ]
